<form id="registrationForm" action="/pay-forget-password-send-mail" method="post" class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal">Wprowadź maila przypisanego do Twojego konta</h1>
    <label for="email" class="sr-only">email</label>
    <input id="email" name="email" type="text" class="form-control" placeholder="email" required autofocus>
    <button class="btn btn-lg btn-block">Zmień hasło</button>
</form>