<h1 class="alert-danger">Nieprawidłowy adres email</h1>
<form id="registrationForm" action="/pay-registration" method="post" class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal">Wprowadź maila przypisanego do Twojego konta</h1>
    <label for="name" class="sr-only">email
        <input id="email" name="email" type="text" class="form-control" placeholder="email" required autofocus>
    </label>
    <button class="btn btn-lg btn-block">Przypomnij hasło</button>
</form>