<!doctype html>
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Płatności On-line</title>
  <meta name="description" content="Payment">
  <meta name="keywords" content="Payment">
  <meta name="author" content="Mikołaj Krawczak">
  <meta http-equiv="X-Ua-Compatible" content="IE=edge">

  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="stylesheet" href="css/main-site.css">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;subset=latin-ext"
        rel="stylesheet">
</head>

<body class="text-center">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">Płatności On-line</h3>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link active" href="">Strona główna</a>
        <a class="nav-link" href="#">Uzytkownicy</a>
        <a class="nav-link" href="#">Płatności</a>
      </nav>
    </div>
  </header>

  <main authorities="main" class="inner cover">
    <h1 class="cover-heading">Witaj ${username}</h1>

  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> &copy; Mikołaj Krawczak 2020 </p>
    </div>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>

<script src="js/bootstrap.min.js"></script>
</body>
</html>